# Cloudflare Pages 配置文件

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

# 环境变量
[env.production.vars]
VITE_API_BASE_URL = "https://icon-search-api.your-domain.workers.dev"
VITE_ENVIRONMENT = "production"

[env.preview.vars]
VITE_API_BASE_URL = "https://icon-search-api-staging.your-domain.workers.dev"
VITE_ENVIRONMENT = "preview"

# 重定向规则
[[redirects]]
from = "/api/*"
to = "https://icon-search-api.your-domain.workers.dev/api/:splat"
status = 200

# 头部设置
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "*.ico"
[headers.values]
Cache-Control = "public, max-age=86400"
