# Cloudflare Pages 部署配置
name = "icon-search-tool"
compatibility_date = "2024-08-07"

# 生产环境配置
[env.production]
name = "icon-search-tool"

# 预发布环境配置
[env.staging]
name = "icon-search-tool-staging"

# 开发环境配置
[env.development]
name = "icon-search-tool-dev"

# Pages 项目配置
[pages]
# 构建输出目录
build_output_dir = "dist"
# 构建命令
build_command = "npm run build"
# Node.js 版本
node_version = "18"

# 环境变量（如需要）
[env.production.vars]
NODE_ENV = "production"

[env.staging.vars]
NODE_ENV = "staging"

[env.development.vars]
NODE_ENV = "development"
