// 图标数据接口
export interface IconData {
  name: string
  category: string
  collection: string
  tags: string[]
}

// 图标集合配置 - 使用 Iconify API
export const iconCollections = [
  { id: 'lucide', name: 'Lucide', prefix: 'lucide' },
  { id: 'heroicons', name: 'Heroicons', prefix: 'heroicons' },
  { id: 'feather', name: 'Feather', prefix: 'feather' },
  { id: 'tabler', name: 'Tabler', prefix: 'tabler' },
  { id: 'material', name: 'Material Design', prefix: 'material-symbols' },
  { id: 'phosphor', name: 'Phosphor', prefix: 'ph' }
]

// 分类中文映射
export const categoryNames: { [key: string]: string } = {
  'all': '全部',
  'general': '通用',
  'arrows': '箭头',
  'communication': '通讯',
  'design': '设计',
  'development': '开发',
  'devices': '设备',
  'files': '文件',
  'finance': '金融',
  'health': '健康',
  'maps': '地图',
  'media': '媒体',
  'nature': '自然',
  'people': '人物',
  'security': '安全',
  'shopping': '购物',
  'social': '社交',
  'system': '系统',
  'text': '文本',
  'transport': '交通',
  'weather': '天气',
  'software': '软件',
  'education': '教育',
  'sports': '运动',
  'food': '食物',
  'travel': '旅行',
  'entertainment': '娱乐',
  'business': '商务',
  'science': '科学',
  'custom': '自定义'
}

// 热门图标数据 - 使用 Iconify 格式
export const popularIcons: IconData[] = [
  // Lucide 图标 (100+ 图标)
  { name: 'lucide:home', category: 'general', collection: 'lucide', tags: ['house', 'main', 'start'] },
  { name: 'lucide:search', category: 'general', collection: 'lucide', tags: ['find', 'look', 'magnify'] },
  { name: 'lucide:user', category: 'people', collection: 'lucide', tags: ['person', 'profile', 'account'] },
  { name: 'lucide:settings', category: 'system', collection: 'lucide', tags: ['config', 'gear', 'options'] },
  { name: 'lucide:heart', category: 'social', collection: 'lucide', tags: ['love', 'like', 'favorite'] },
  { name: 'lucide:star', category: 'social', collection: 'lucide', tags: ['rating', 'favorite', 'bookmark'] },
  { name: 'lucide:mail', category: 'communication', collection: 'lucide', tags: ['email', 'message', 'envelope'] },
  { name: 'lucide:phone', category: 'communication', collection: 'lucide', tags: ['call', 'telephone', 'mobile'] },
  { name: 'lucide:download', category: 'arrows', collection: 'lucide', tags: ['save', 'export', 'get'] },
  { name: 'lucide:upload', category: 'arrows', collection: 'lucide', tags: ['import', 'send', 'put'] },
  { name: 'lucide:edit', category: 'design', collection: 'lucide', tags: ['pencil', 'modify', 'change'] },
  { name: 'lucide:trash-2', category: 'general', collection: 'lucide', tags: ['delete', 'remove', 'bin'] },
  { name: 'lucide:copy', category: 'files', collection: 'lucide', tags: ['duplicate', 'clone', 'paste'] },
  { name: 'lucide:share-2', category: 'social', collection: 'lucide', tags: ['send', 'distribute', 'export'] },
  { name: 'lucide:lock', category: 'security', collection: 'lucide', tags: ['secure', 'private', 'protected'] },
  { name: 'lucide:unlock', category: 'security', collection: 'lucide', tags: ['open', 'access', 'public'] },
  { name: 'lucide:eye', category: 'general', collection: 'lucide', tags: ['view', 'see', 'visible'] },
  { name: 'lucide:eye-off', category: 'general', collection: 'lucide', tags: ['hide', 'invisible', 'hidden'] },
  { name: 'lucide:check', category: 'general', collection: 'lucide', tags: ['done', 'complete', 'success'] },
  { name: 'lucide:x', category: 'general', collection: 'lucide', tags: ['close', 'cancel', 'remove'] },
  { name: 'lucide:plus', category: 'general', collection: 'lucide', tags: ['add', 'create', 'new'] },
  { name: 'lucide:minus', category: 'general', collection: 'lucide', tags: ['subtract', 'remove', 'less'] },
  { name: 'lucide:arrow-right', category: 'arrows', collection: 'lucide', tags: ['next', 'forward', 'continue'] },
  { name: 'lucide:arrow-left', category: 'arrows', collection: 'lucide', tags: ['back', 'previous', 'return'] },
  { name: 'lucide:arrow-up', category: 'arrows', collection: 'lucide', tags: ['top', 'increase', 'rise'] },
  { name: 'lucide:arrow-down', category: 'arrows', collection: 'lucide', tags: ['bottom', 'decrease', 'fall'] },
  { name: 'lucide:menu', category: 'general', collection: 'lucide', tags: ['hamburger', 'navigation', 'list'] },
  { name: 'lucide:more-horizontal', category: 'general', collection: 'lucide', tags: ['options', 'dots', 'menu'] },
  { name: 'lucide:more-vertical', category: 'general', collection: 'lucide', tags: ['options', 'dots', 'menu'] },
  { name: 'lucide:calendar', category: 'general', collection: 'lucide', tags: ['date', 'schedule', 'time'] },
  { name: 'lucide:clock', category: 'general', collection: 'lucide', tags: ['time', 'schedule', 'hour'] },
  { name: 'lucide:bell', category: 'communication', collection: 'lucide', tags: ['notification', 'alert', 'ring'] },
  { name: 'lucide:bookmark', category: 'general', collection: 'lucide', tags: ['save', 'mark', 'favorite'] },
  { name: 'lucide:flag', category: 'general', collection: 'lucide', tags: ['mark', 'report', 'country'] },
  { name: 'lucide:folder', category: 'files', collection: 'lucide', tags: ['directory', 'storage', 'organize'] },
  { name: 'lucide:file', category: 'files', collection: 'lucide', tags: ['document', 'paper', 'text'] },
  { name: 'lucide:image', category: 'media', collection: 'lucide', tags: ['picture', 'photo', 'graphic'] },
  { name: 'lucide:video', category: 'media', collection: 'lucide', tags: ['movie', 'film', 'play'] },
  { name: 'lucide:music', category: 'media', collection: 'lucide', tags: ['audio', 'sound', 'song'] },
  { name: 'lucide:camera', category: 'media', collection: 'lucide', tags: ['photo', 'picture', 'capture'] },
  { name: 'lucide:wifi', category: 'devices', collection: 'lucide', tags: ['internet', 'connection', 'network'] },
  { name: 'lucide:bluetooth', category: 'devices', collection: 'lucide', tags: ['wireless', 'connection', 'pair'] },
  { name: 'lucide:battery', category: 'devices', collection: 'lucide', tags: ['power', 'charge', 'energy'] },
  { name: 'lucide:globe', category: 'general', collection: 'lucide', tags: ['world', 'earth', 'international'] },
  { name: 'lucide:map-pin', category: 'maps', collection: 'lucide', tags: ['location', 'place', 'marker'] },
  { name: 'lucide:navigation', category: 'maps', collection: 'lucide', tags: ['compass', 'direction', 'guide'] },
  { name: 'lucide:car', category: 'transport', collection: 'lucide', tags: ['vehicle', 'auto', 'drive'] },
  { name: 'lucide:plane', category: 'transport', collection: 'lucide', tags: ['airplane', 'flight', 'travel'] },
  { name: 'lucide:train', category: 'transport', collection: 'lucide', tags: ['railway', 'metro', 'subway'] },
  { name: 'lucide:sun', category: 'weather', collection: 'lucide', tags: ['sunny', 'bright', 'day'] },
  { name: 'lucide:moon', category: 'weather', collection: 'lucide', tags: ['night', 'dark', 'sleep'] },
  { name: 'lucide:cloud', category: 'weather', collection: 'lucide', tags: ['sky', 'overcast', 'storage'] },
  { name: 'lucide:umbrella', category: 'weather', collection: 'lucide', tags: ['rain', 'protection', 'cover'] },
  { name: 'lucide:zap', category: 'general', collection: 'lucide', tags: ['lightning', 'power', 'energy'] },
  { name: 'lucide:shield', category: 'security', collection: 'lucide', tags: ['protection', 'secure', 'safety'] },
  { name: 'lucide:key', category: 'security', collection: 'lucide', tags: ['password', 'access', 'unlock'] },
  { name: 'lucide:users', category: 'people', collection: 'lucide', tags: ['group', 'team', 'multiple'] },
  { name: 'lucide:user-plus', category: 'people', collection: 'lucide', tags: ['add-user', 'invite', 'new'] },
  { name: 'lucide:user-minus', category: 'people', collection: 'lucide', tags: ['remove-user', 'delete', 'kick'] },
  { name: 'lucide:shopping-cart', category: 'shopping', collection: 'lucide', tags: ['cart', 'buy', 'purchase'] },
  { name: 'lucide:credit-card', category: 'finance', collection: 'lucide', tags: ['payment', 'money', 'card'] },
  { name: 'lucide:dollar-sign', category: 'finance', collection: 'lucide', tags: ['money', 'price', 'cost'] },
  { name: 'lucide:trending-up', category: 'arrows', collection: 'lucide', tags: ['growth', 'increase', 'chart'] },
  { name: 'lucide:trending-down', category: 'arrows', collection: 'lucide', tags: ['decline', 'decrease', 'chart'] },
  { name: 'lucide:bar-chart', category: 'general', collection: 'lucide', tags: ['chart', 'graph', 'data'] },
  { name: 'lucide:pie-chart', category: 'general', collection: 'lucide', tags: ['chart', 'graph', 'statistics'] },
  { name: 'lucide:activity', category: 'general', collection: 'lucide', tags: ['pulse', 'heartbeat', 'monitor'] },
  { name: 'lucide:cpu', category: 'devices', collection: 'lucide', tags: ['processor', 'chip', 'computer'] },
  { name: 'lucide:hard-drive', category: 'devices', collection: 'lucide', tags: ['storage', 'disk', 'data'] },
  { name: 'lucide:monitor', category: 'devices', collection: 'lucide', tags: ['screen', 'display', 'computer'] },
  { name: 'lucide:smartphone', category: 'devices', collection: 'lucide', tags: ['mobile', 'phone', 'device'] },
  { name: 'lucide:tablet', category: 'devices', collection: 'lucide', tags: ['ipad', 'device', 'mobile'] },
  { name: 'lucide:laptop', category: 'devices', collection: 'lucide', tags: ['computer', 'notebook', 'pc'] },
  { name: 'lucide:headphones', category: 'media', collection: 'lucide', tags: ['audio', 'sound', 'music'] },
  { name: 'lucide:mic', category: 'media', collection: 'lucide', tags: ['microphone', 'record', 'voice'] },
  { name: 'lucide:volume-2', category: 'media', collection: 'lucide', tags: ['sound', 'audio', 'speaker'] },
  { name: 'lucide:volume-x', category: 'media', collection: 'lucide', tags: ['mute', 'silent', 'no-sound'] },
  { name: 'lucide:play', category: 'media', collection: 'lucide', tags: ['start', 'begin', 'video'] },
  { name: 'lucide:pause', category: 'media', collection: 'lucide', tags: ['stop', 'break', 'video'] },
  { name: 'lucide:skip-forward', category: 'media', collection: 'lucide', tags: ['next', 'forward', 'video'] },
  { name: 'lucide:skip-back', category: 'media', collection: 'lucide', tags: ['previous', 'back', 'video'] },
  { name: 'lucide:repeat', category: 'media', collection: 'lucide', tags: ['loop', 'cycle', 'again'] },
  { name: 'lucide:shuffle', category: 'media', collection: 'lucide', tags: ['random', 'mix', 'playlist'] },

  // 软件图标 (50+ 图标)
  { name: 'lucide:code', category: 'software', collection: 'lucide', tags: ['programming', 'development', 'coding'] },
  { name: 'lucide:terminal', category: 'software', collection: 'lucide', tags: ['command', 'console', 'shell'] },
  { name: 'lucide:database', category: 'software', collection: 'lucide', tags: ['data', 'storage', 'sql'] },
  { name: 'lucide:git-branch', category: 'software', collection: 'lucide', tags: ['git', 'version', 'control'] },
  { name: 'lucide:github', category: 'software', collection: 'lucide', tags: ['git', 'repository', 'code'] },
  { name: 'lucide:chrome', category: 'software', collection: 'lucide', tags: ['browser', 'google', 'web'] },
  { name: 'lucide:firefox', category: 'software', collection: 'lucide', tags: ['browser', 'mozilla', 'web'] },
  { name: 'lucide:figma', category: 'software', collection: 'lucide', tags: ['design', 'ui', 'prototype'] },
  { name: 'lucide:slack', category: 'software', collection: 'lucide', tags: ['chat', 'team', 'communication'] },
  { name: 'lucide:discord', category: 'software', collection: 'lucide', tags: ['chat', 'gaming', 'voice'] },
  { name: 'lucide:youtube', category: 'software', collection: 'lucide', tags: ['video', 'streaming', 'google'] },
  { name: 'lucide:instagram', category: 'software', collection: 'lucide', tags: ['social', 'photo', 'meta'] },
  { name: 'lucide:twitter', category: 'software', collection: 'lucide', tags: ['social', 'x', 'microblog'] },
  { name: 'lucide:facebook', category: 'software', collection: 'lucide', tags: ['social', 'meta', 'network'] },
  { name: 'lucide:linkedin', category: 'software', collection: 'lucide', tags: ['professional', 'network', 'career'] },
  { name: 'tabler:brand-adobe', category: 'software', collection: 'tabler', tags: ['adobe', 'creative', 'design'] },
  { name: 'tabler:brand-photoshop', category: 'software', collection: 'tabler', tags: ['photoshop', 'adobe', 'image'] },
  { name: 'tabler:brand-illustrator', category: 'software', collection: 'tabler', tags: ['illustrator', 'adobe', 'vector'] },
  { name: 'tabler:brand-sketch', category: 'software', collection: 'tabler', tags: ['sketch', 'design', 'ui'] },
  { name: 'tabler:brand-vscode', category: 'software', collection: 'tabler', tags: ['vscode', 'editor', 'microsoft'] },
  { name: 'tabler:brand-notion', category: 'software', collection: 'tabler', tags: ['notion', 'notes', 'productivity'] },
  { name: 'tabler:brand-trello', category: 'software', collection: 'tabler', tags: ['trello', 'kanban', 'project'] },
  { name: 'tabler:brand-zoom', category: 'software', collection: 'tabler', tags: ['zoom', 'video', 'meeting'] },
  { name: 'tabler:brand-teams', category: 'software', collection: 'tabler', tags: ['teams', 'microsoft', 'collaboration'] },
  { name: 'tabler:brand-office', category: 'software', collection: 'tabler', tags: ['office', 'microsoft', 'productivity'] },
  { name: 'tabler:brand-windows', category: 'software', collection: 'tabler', tags: ['windows', 'microsoft', 'os'] },
  { name: 'tabler:brand-apple', category: 'software', collection: 'tabler', tags: ['apple', 'mac', 'ios'] },
  { name: 'tabler:brand-android', category: 'software', collection: 'tabler', tags: ['android', 'google', 'mobile'] },
  { name: 'tabler:brand-docker', category: 'software', collection: 'tabler', tags: ['docker', 'container', 'devops'] },
  { name: 'tabler:brand-kubernetes', category: 'software', collection: 'tabler', tags: ['kubernetes', 'k8s', 'orchestration'] },
  { name: 'tabler:brand-aws', category: 'software', collection: 'tabler', tags: ['aws', 'amazon', 'cloud'] },
  { name: 'tabler:brand-azure', category: 'software', collection: 'tabler', tags: ['azure', 'microsoft', 'cloud'] },
  { name: 'tabler:brand-google-cloud', category: 'software', collection: 'tabler', tags: ['gcp', 'google', 'cloud'] },
  { name: 'tabler:brand-react', category: 'software', collection: 'tabler', tags: ['react', 'javascript', 'frontend'] },
  { name: 'tabler:brand-vue', category: 'software', collection: 'tabler', tags: ['vue', 'javascript', 'frontend'] },
  { name: 'tabler:brand-angular', category: 'software', collection: 'tabler', tags: ['angular', 'typescript', 'frontend'] },
  { name: 'tabler:brand-nodejs', category: 'software', collection: 'tabler', tags: ['nodejs', 'javascript', 'backend'] },
  { name: 'tabler:brand-python', category: 'software', collection: 'tabler', tags: ['python', 'programming', 'language'] },
  { name: 'tabler:brand-java', category: 'software', collection: 'tabler', tags: ['java', 'programming', 'language'] },
  { name: 'tabler:brand-javascript', category: 'software', collection: 'tabler', tags: ['javascript', 'js', 'programming'] },
  { name: 'tabler:brand-typescript', category: 'software', collection: 'tabler', tags: ['typescript', 'ts', 'programming'] },
  { name: 'tabler:brand-html5', category: 'software', collection: 'tabler', tags: ['html', 'web', 'markup'] },
  { name: 'tabler:brand-css3', category: 'software', collection: 'tabler', tags: ['css', 'style', 'web'] },
  { name: 'tabler:brand-sass', category: 'software', collection: 'tabler', tags: ['sass', 'css', 'preprocessor'] },
  { name: 'tabler:brand-tailwind', category: 'software', collection: 'tabler', tags: ['tailwind', 'css', 'framework'] },
  { name: 'tabler:brand-bootstrap', category: 'software', collection: 'tabler', tags: ['bootstrap', 'css', 'framework'] },
  { name: 'tabler:brand-mysql', category: 'software', collection: 'tabler', tags: ['mysql', 'database', 'sql'] },
  { name: 'tabler:brand-postgresql', category: 'software', collection: 'tabler', tags: ['postgresql', 'database', 'sql'] },
  { name: 'tabler:brand-mongodb', category: 'software', collection: 'tabler', tags: ['mongodb', 'database', 'nosql'] },
  { name: 'tabler:brand-redis', category: 'software', collection: 'tabler', tags: ['redis', 'cache', 'database'] },
  { name: 'tabler:brand-solidworks', category: 'software', collection: 'tabler', tags: ['solidworks', 'cad', '3d'] },
  { name: 'tabler:brand-autocad', category: 'software', collection: 'tabler', tags: ['autocad', 'cad', 'design'] },
  { name: 'tabler:brand-blender', category: 'software', collection: 'tabler', tags: ['blender', '3d', 'modeling'] },
  { name: 'tabler:brand-unity', category: 'software', collection: 'tabler', tags: ['unity', 'game', 'engine'] },
  { name: 'tabler:brand-unreal-engine', category: 'software', collection: 'tabler', tags: ['unreal', 'game', 'engine'] }
]
